project:
  type: website
  output-dir: docs
website:
  title: "Hoomie studio"
  navbar:
    backgroundcolor: '#808080'
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - dashboard.qmd

    
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    fontcolor: '#808080'
    monofont: courier new

editor: visual
