project:
  type: website
  output-dir: docs
website:
  title: "Hoomie studio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme:
      - cosmo
      - sandstone
    css: styles.css
    toc: true

editor: visual

